import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.CartPage;
import org.example.CheckOutPage;
import org.example.HomePage;
import org.example.LoginPage;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.Assert;
import org.testng.annotations.Test;

public class SmokeTest {
        WebDriver driver;
        LoginPage login = new LoginPage();
        HomePage home = new HomePage();
        CheckOutPage checkout = new CheckOutPage();
        CartPage cart = new CartPage();
    @Test
        public void SmokeTest() throws InterruptedException {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.navigate().to("https://www.saucedemo.com/v1/");
        driver.manage().window().maximize();
        Thread.sleep(1000);
        login.usernameElement(driver).sendKeys("standard_user");
        Thread.sleep(1000);
        login.passwordElement(driver).sendKeys("secret_sauce");
        Thread.sleep(1000);
        login.LoginButtonElement(driver).click();
        Thread.sleep(1000);
        Select DropDown = new Select(home.DropDownElement(driver));
        DropDown.selectByVisibleText("Price (high to low)");
        Thread.sleep(4000);
        home.HighestElement(driver).click();
        String Expectedprice = "49.99";
        String Actualprice = home.Highestprice(driver).getText();
        Assert.assertEquals(Actualprice.contains(Expectedprice), true);
        Thread.sleep(2000);
        home.AddToCart(driver).click();
        Thread.sleep(3000);
        driver.navigate().back();
        Thread.sleep(1000);
        Select DropDown2 = new Select(home.DropDownElement(driver));
        DropDown2.selectByVisibleText("Price (low to high)");
        Thread.sleep(4000);
        home.LowestElement(driver).click();
        String Expectedprice2 = "7.99";
        String Actualprice2 = home.Lowestprice(driver).getText();
        Assert.assertEquals(Actualprice2.contains(Expectedprice2), true);
        Thread.sleep(2000);
        home.AddToCart(driver).click();
        Thread.sleep(3000);
        driver.navigate().back();
        Thread.sleep(1000);
        cart.CartElement(driver).click();
        Thread.sleep(3000);
        String Expectedprice3 = "49.99";
        String Actualprice3 = cart.Highestprice(driver).getText();
        Assert.assertEquals(Actualprice3.contains(Expectedprice3), true);
        String Expectedprice4 = "7.99";
        String Actualprice4 = cart.Lowestprice(driver).getText();
        Assert.assertEquals(Actualprice4.contains(Expectedprice4), true);
        Thread.sleep(3000);
        cart.RemoveRandomItem(driver).click();
        Thread.sleep(1000);
        cart.CheckOutElement(driver).click();
        Thread.sleep(2000);
        checkout.firstnameElement(driver).sendKeys("Aml Mostafa");
        checkout.lastnameElement(driver).sendKeys("Maryem Abdelsalam");
        checkout.PostalCodeElement(driver).sendKeys("123");
        Thread.sleep(3000);
        checkout.ContinueElement(driver).click();
        Thread.sleep(2000);
        checkout.FinsishElement(driver).click();
        String ExpectedMessage = "THANK YOU FOR YOUR ORDER";
        String ActualMessage = checkout.CompleteHeaderElement(driver).getText();
        Assert.assertEquals(ActualMessage.contains(ExpectedMessage),true);
        Thread.sleep(2000);
        driver.close();
    }
}
